version: '2'
services:
  knote:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - 8080
    environment:
      - VIRTUAL_HOST=jsknote.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jsknote.com
      - LETSENCRYPT_EMAIL=js@jsknote.com
    networks:
      - reverse-proxy
    restart: always

networks:
    reverse-proxy:
        external:
            name: reverse-proxy
